; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = bluepill_f103c8
framework = zephyr

[platformio]
default_envs = bluepill_f103c8_controller

[env:bluepill_f103c8_controller]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;controller.conf" -DDTC_OVERLAY_FILE="boards/app_controller.overlay"

[env:bluepill_f103c8_target]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;target.conf" -DDTC_OVERLAY_FILE="boards/app_target.overlay"

[env:bluepill_f103c8_target_prio1]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;target.conf;target_prio1.conf" -DDTC_OVERLAY_FILE="boards/app_target.overlay"

[env:bluepill_f103c8_jitter_controller]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;jitter_controller.conf" -DDTC_OVERLAY_FILE="boards/app_controller.overlay"

[env:bluepill_f103c8_jitter_target]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;jitter_target.conf" -DDTC_OVERLAY_FILE="boards/app_target.overlay"

[env:bluepill_f103c8_mco_hse]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;controller.conf;mco_hse.conf" -DDTC_OVERLAY_FILE="boards/app_controller.overlay"

[env:bluepill_f103c8_mco_sysclk]
extends = env
board_build.zephyr.cmake_extra_args = -DCONF_FILE="prj.conf;controller.conf;mco_sysclk.conf" -DDTC_OVERLAY_FILE="boards/app_controller.overlay"
