#!/usr/bin/env python3
"""Calculate the analytical network precision boundary for each iteration.

The write-up defines the central-master precision boundary as:

    Π_central = ε + Γ

where
- ε is the worst-case SPI transaction jitter across the network, and
- Γ is the worst-case drift divergence of the internal HSI oscillators.

This script computes that value for each versioned metrics report in the
no-load and under-load scenarios, using the data already generated by
scripts/calc_metrics.py.

The practical approximation used here is:
- ε = max(child epsilon_us)
- Γ = max(child abs_theta_us_max)

The result is therefore the upper-bound temporal disagreement between any
worker/child tuple before correction.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def discover_default_metrics(root: Path, pattern: str) -> List[Path]:
    matches = sorted(root.glob(pattern))
    if not matches:
        raise FileNotFoundError(f"No files matching '{pattern}' were found under {root}")
    return matches


def validate_version_order(paths: Sequence[Path], scenario_name: str) -> List[Path]:
    if not paths:
        raise ValueError(f"No {scenario_name} metric files were provided")
    if len(paths) < 1:
        raise ValueError(f"Need at least one metric file for {scenario_name}")
    return list(paths)


def network_precision_boundary(report: Dict[str, Any]) -> Dict[str, float]:
    child_drift = report.get("drift_offset", {}).get("per_child", [])
    if not child_drift:
        raise ValueError("Missing drift_offset.per_child data in report")

    child_jitter = report.get("jitter", {}).get("spi_transaction_jitter", {}).get("per_child", [])
    if not child_jitter:
        raise ValueError("Missing jitter.spi_transaction_jitter.per_child data in report")

    gamma_us = max(float(row["abs_theta_us_max"]) for row in child_drift)
    epsilon_us = max(float(row["epsilon_us"]) for row in child_jitter)
    boundary_us = gamma_us + epsilon_us

    return {
        "gamma_us": gamma_us,
        "epsilon_us": epsilon_us,
        "boundary_us": boundary_us,
        "gamma_ms": gamma_us / 1000.0,
        "epsilon_ms": epsilon_us / 1000.0,
        "boundary_ms": boundary_us / 1000.0,
    }


def build_scenario_rows(paths: Sequence[Path], scenario_name: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for path in paths:
        report = load_json(path)
        boundary = network_precision_boundary(report)
        rows.append(
            {
                "version": path.stem.replace("metrics_load_", "").replace("metrics_", "").upper().replace("_", ""),
                "file": str(path),
                "scenario": scenario_name,
                **boundary,
            }
        )
    return rows


def render_table(rows: Sequence[Dict[str, Any]], scenario_name: str) -> str:
    if not rows:
        return f"{scenario_name}: no data"

    lines = [
        f"\n{scenario_name}",
        "Version  epsilon_ms  gamma_ms  boundary_ms  epsilon_us  gamma_us  boundary_us",
        "-" * 90,
    ]
    for row in rows:
        lines.append(
            f"{row['version']:<8} {row['epsilon_ms']:>10.3f} {row['gamma_ms']:>8.3f} {row['boundary_ms']:>12.3f} "
            f"{row['epsilon_us']:>10.0f} {row['gamma_us']:>8.0f} {row['boundary_us']:>11.0f}"
        )
    lines.append("-" * 90)
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute the central-master network precision boundary Π_central = ε + Γ for no-load and under-load datasets."
    )
    parser.add_argument(
        "--normal-metrics",
        nargs="+",
        type=Path,
        default=None,
        help="Ordered JSON reports for the no-load scenario (e.g. metrics/metrics_V1.json metrics/metrics_V2.json ...)",
    )
    parser.add_argument(
        "--load-metrics",
        nargs="+",
        type=Path,
        default=None,
        help="Ordered JSON reports for the under-load scenario (e.g. metrics/metrics_load_V1.json metrics/metrics_load_V2.json ...)",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root used for auto-discovery; defaults to the workspace root.",
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        default=None,
        help="Optional path to write the full boundary summary as JSON.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.normal_metrics is None and args.load_metrics is None:
        normal_paths = discover_default_metrics(args.root / "metrics", "metrics_V*.json")
        load_paths = discover_default_metrics(args.root / "metrics", "metrics_load_V*.json")
    else:
        normal_paths = validate_version_order(args.normal_metrics or [], "no-load")
        load_paths = validate_version_order(args.load_metrics or [], "under-load")

    scenario_rows: Dict[str, List[Dict[str, Any]]] = {}
    if args.normal_metrics is not None or (args.normal_metrics is None and args.load_metrics is None):
        scenario_rows["No-load"] = build_scenario_rows(normal_paths, "No-load")
    if args.load_metrics is not None or (args.normal_metrics is None and args.load_metrics is None):
        scenario_rows["Under-load"] = build_scenario_rows(load_paths, "Under-load")

    for scenario_name, rows in scenario_rows.items():
        print(render_table(rows, scenario_name))

    if args.json_out is not None:
        payload = {
            "scenarios": {
                scenario_name: rows
                for scenario_name, rows in scenario_rows.items()
            }
        }
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print()
        print(f"wrote JSON boundary report: {args.json_out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
