#!/usr/bin/env python3
"""Compare each version against V1 for offset, precision, and SPI jitter.

This script reads the versioned metric JSON files generated by calc_metrics.py and
computes approximate Welch-style p-values using the summary statistics available in
those files. It is designed for the repo's no-load and under-load reports where
raw per-sample data is not stored.

The comparison is intended to answer:
- Did the mean offset change significantly from V1?
- Did the mean precision change significantly from V1?
- Did the SPI transaction jitter change significantly from V1?

Usage:
    python3 scripts/compare_versions.py
    python3 scripts/compare_versions.py \
        --normal-metrics metrics/metrics_V1.json metrics/metrics_V2.json metrics/metrics_V3.json metrics/metrics_V4.json \
        --load-metrics metrics/metrics_load_V1.json metrics/metrics_load_V2.json metrics/metrics_load_V3.json metrics/metrics_load_V4.json
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from statistics import NormalDist
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

try:  # Optional dependency; use if available for better t-distribution tail values.
    from scipy.stats import t as student_t
except Exception:  # pragma: no cover - optional dependency
    student_t = None

ALPHA = 0.05


class MetricComparisonError(RuntimeError):
    """Raised for invalid input metric files or unsupported metric shapes."""


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def weighted_mean_offset(report: Dict[str, Any]) -> Tuple[float, float, int]:
    """Return (mean, stddev, n) for the aggregate drift-offset metric.

    The reports store per-child theta_us_mean and theta_us_stddev values with sample
    counts. We combine the children by weighting by their sample counts.
    """
    child_rows = report.get("drift_offset", {}).get("per_child", [])
    if not child_rows:
        raise MetricComparisonError(f"Missing drift_offset.per_child data in {report}")

    n_total = sum(int(row["samples"]) for row in child_rows)
    if n_total <= 0:
        raise MetricComparisonError("Drift offset sample count is zero")

    weighted_mean = sum(int(row["samples"]) * float(row["theta_us_mean"]) for row in child_rows) / n_total

    # Approximate the combined variance from the child distributions, adding the spread
    # between child means to capture across-child variation.
    between_var = 0.0
    within_var = 0.0
    for row in child_rows:
        n = int(row["samples"])
        value = float(row["theta_us_mean"])
        s = float(row["theta_us_stddev"])
        within_var += (n - 1) * (s ** 2)
        between_var += n * (value - weighted_mean) ** 2

    combined_df = max(n_total - 1, 1)
    combined_var = (within_var + between_var) / combined_df
    combined_std = math.sqrt(combined_var)
    return weighted_mean, combined_std, n_total


def precision_summary(report: Dict[str, Any]) -> Tuple[float, float, int]:
    precision = report.get("precision", {})
    n = int(precision.get("cycles_evaluated", 0) or 0)
    mean = float(precision.get("precision_us_mean", 0.0) or 0.0)
    stddev = float(precision.get("precision_us_stddev", 0.0) or 0.0)
    return mean, stddev, n


def jitter_summary(report: Dict[str, Any]) -> Tuple[float, float, int]:
    rows = report.get("jitter", {}).get("spi_transaction_jitter", {}).get("per_child", [])
    if not rows:
        raise MetricComparisonError("Missing jitter.spi_transaction_jitter.per_child data")

    epsilons = [float(row["epsilon_us"]) for row in rows]
    mean = sum(epsilons) / len(epsilons)
    if len(epsilons) > 1:
        stddev = math.sqrt(sum((x - mean) ** 2 for x in epsilons) / (len(epsilons) - 1))
    else:
        stddev = 0.0
    return mean, stddev, len(epsilons)


def welch_t_test(mean1: float, std1: float, n1: int, mean2: float, std2: float, n2: int) -> Optional[float]:
    """Return the two-sided p-value for a Welch t-test via summary stats."""
    if n1 <= 1 or n2 <= 1:
        return None
    if std1 <= 0 and std2 <= 0:
        return None

    var1 = std1 ** 2
    var2 = std2 ** 2
    se = math.sqrt((var1 / n1) + (var2 / n2))
    if se == 0:
        return None

    t_stat = abs(mean1 - mean2) / se
    numerator = (var1 / n1 + var2 / n2) ** 2
    denominator = ((var1 / n1) ** 2 / (n1 - 1)) + ((var2 / n2) ** 2 / (n2 - 1))
    if denominator <= 0:
        return None
    df = numerator / denominator

    if student_t is not None:
        p_value = 2.0 * student_t.sf(t_stat, df)
        return float(p_value)

    # Fall back to a normal approximation if SciPy is not installed.
    z = t_stat
    p_value = 2.0 * (1.0 - NormalDist().cdf(z))
    return float(p_value)


def compare_metric(label: str, baseline: Dict[str, Any], candidate: Dict[str, Any], alpha: float = ALPHA) -> Dict[str, Any]:
    if label == "mean_offset":
        base_mean, base_std, base_n = weighted_mean_offset(baseline)
        cand_mean, cand_std, cand_n = weighted_mean_offset(candidate)
    elif label == "precision":
        base_mean, base_std, base_n = precision_summary(baseline)
        cand_mean, cand_std, cand_n = precision_summary(candidate)
    elif label == "spi_jitter":
        base_mean, base_std, base_n = jitter_summary(baseline)
        cand_mean, cand_std, cand_n = jitter_summary(candidate)
    else:
        raise ValueError(f"Unsupported metric label: {label}")

    p_value = welch_t_test(base_mean, base_std, base_n, cand_mean, cand_std, cand_n)
    significant = p_value is not None and p_value < alpha

    return {
        "metric": label,
        "baseline_mean": base_mean,
        "candidate_mean": cand_mean,
        "mean_delta": cand_mean - base_mean,
        "p_value": p_value,
        "significant": significant,
        "baseline_n": base_n,
        "candidate_n": cand_n,
    }


def validate_version_order(paths: Sequence[Path], scenario_name: str) -> List[Path]:
    if not paths:
        raise MetricComparisonError(f"No {scenario_name} metric files were provided")
    if len(paths) < 2:
        raise MetricComparisonError(f"Need at least V1 and one later version for {scenario_name}")

    v1 = paths[0]
    if v1.name.lower().find("v1") == -1:
        raise MetricComparisonError(f"Expected the first {scenario_name} metric file to be V1, got {v1.name}")
    return list(paths)


def discover_default_metrics(root: Path, pattern: str) -> List[Path]:
    matches = sorted(root.glob(pattern))
    if not matches:
        raise MetricComparisonError(f"No files matching pattern '{pattern}' were found under {root}")
    return matches


def render_table(rows: Sequence[Dict[str, Any]], scenario: str) -> str:
    lines = [
        f"\n{scenario}",
        "Version  Metric            V1 mean       New mean      Delta        p-value      Significant",
        "-" * 110,
    ]

    for item in rows:
        version = item["version"]
        metric = item["metric"]
        v1_mean = item["baseline_mean"]
        new_mean = item["candidate_mean"]
        delta = item["mean_delta"]
        p_value = item["p_value"]
        sig = item["significant"]

        p_text = "N/A" if p_value is None else f"{p_value:.3e}"
        lines.append(
            f"{version:<8} {metric:<17} {v1_mean:>12.3f} {new_mean:>12.3f} {delta:>12.3f} {p_text:>12} {str(sig):>12}"
        )

    lines.append("-" * 110)
    return "\n".join(lines)


def compare_all_versions_against_v1(baseline_report: Dict[str, Any], version_reports: Sequence[Tuple[str, Dict[str, Any]]], alpha: float = ALPHA) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    for version, report in version_reports:
        if version == "V1":
            continue
        for metric_name, metric_label in (("mean_offset", "mean_offset"), ("precision", "precision"), ("spi_jitter", "spi_jitter")):
            comparison = compare_metric(metric_label, baseline_report, report, alpha=alpha)
            comparison["version"] = version
            comparison["metric_name"] = metric_name
            results.append(comparison)
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare later versions to V1 on mean offset, precision, and SPI transaction jitter.")
    parser.add_argument(
        "--normal-metrics",
        nargs="+",
        type=Path,
        help="Ordered JSON files for the no-load scenario, starting with V1 (e.g. metrics_V1.json metrics_V2.json metrics_V3.json metrics_V4.json)",
    )
    parser.add_argument(
        "--load-metrics",
        nargs="+",
        type=Path,
        help="Ordered JSON files for the under-load scenario, starting with V1 (e.g. metrics_load_V1.json metrics_load_V2.json metrics_load_V3.json metrics_load_V4.json)",
    )
    parser.add_argument("--alpha", type=float, default=ALPHA, help=f"Significance threshold; default {ALPHA}")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent, help="Repository root; defaults to the workspace root")
    args = parser.parse_args()

    if args.normal_metrics is None and args.load_metrics is None:
        normal_files = discover_default_metrics(args.root / "metrics", "metrics_V*.json")
        load_files = discover_default_metrics(args.root / "metrics", "metrics_load_V*.json")
    else:
        normal_files = validate_version_order(args.normal_metrics or [], "no-load") if args.normal_metrics else []
        load_files = validate_version_order(args.load_metrics or [], "load") if args.load_metrics else []

    if not args.normal_metrics and not args.load_metrics:
        # The auto-discovery path already populated the files.
        pass

    def build_report_pairs(paths: Sequence[Path]) -> List[Tuple[str, Dict[str, Any]]]:
        ordered_paths = validate_version_order(paths, "scenario")
        return [(path.stem.replace("metrics_load_", "").replace("metrics_", "").upper().replace("_", ""), load_json(path)) for path in ordered_paths]

    if args.normal_metrics:
        normal_pairs = build_report_pairs(normal_files)
        baseline_normal = dict(normal_pairs[0][1])
        normal_results = compare_all_versions_against_v1(baseline_normal, normal_pairs, alpha=args.alpha)
        print(render_table(normal_results, "No-load scenario"))

    if args.load_metrics:
        load_pairs = build_report_pairs(load_files)
        baseline_load = dict(load_pairs[0][1])
        load_results = compare_all_versions_against_v1(baseline_load, load_pairs, alpha=args.alpha)
        print(render_table(load_results, "Under-load scenario"))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
